### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by sunny20160530** [wustor/AndroidComponent#1]
您好，我把项目导进AS，没报什么错， 但是运行按钮旁边的module都是红色叉号，请问是什么问题

**Comment by wustor** [comment]
Android Studio是否是最新版本，Gradle插件版本

**Comment by sunny20160530** [comment]
今天下载zip就可以了，上次是git clone 的， 不知道什么原因，我的AS是3.0.1的，gradle4.1的

**Comment by wustor** [comment]
能跑起来就行，我抽空看一下

**Comment by sundyfly** [comment]
麻蛋，不知道更新了怎么。卸载再安装都不行。
