### ISSUE TITLE
不同module之间传值的问题

### ISSUE THREAD

**Issue by androidXiaoHao** [wustor/AndroidComponent#3]
你好，文章中说到“不管是组件单独调试还是所有的Module一起运行对于从ModuleA跳转到ModuleB都是不需要传参的，但是很多时候不同的Module间跳转是需要传参的。而对于一些入口参数比较复杂的或者动态的参数，我们可以继续在debug目录下新建一个Activity来配置我们单Module调试所需要的参数”。
这一点不是很明白，比如ModuleB作为一个单独的app运行后进入ModuleB中的一个页面，而这个页面能否正常展示是需要得到一些动态的值的，大牛能否详细说下？谢谢

**Comment by wustor** [comment]
刚换工作，周六修复所有问题

**Comment by androidXiaoHao** [comment]
感谢大牛的奉献精神，期待中

**Comment by wustor** [comment]
是这个样子的，就是单独调试的时候，入口是另外一个Activity，也会有单独的Application，所以你可以在Application或者Activity中配置相应的参数，这样就可以进行调试了
