### ISSUE TITLE
对于公用的activity应该如何放置的问题

### ISSUE THREAD

**Issue by smileCH** [wustor/AndroidComponent#4]
作者你好，比如现在在goodsModule和orderModule中都需要用到activityA、activityB等等好几个activity，那么我应该将这几个公用的activity放到哪呢？放到baseModule里，然后其他组件去依赖，从而就可以使用到这几个activity还是？总感觉这种做法不合理，毕竟设置baseModule的初衷只是为了放置一些通用的工具类啥的，针对上述问题，不知道作者在实际项目中是如何处理的？

**Comment by wustor** [comment]
你需要用到的Activity属于哪个Module就放在哪个Module里面，然后谁需要用到它就直接通过路由去通信就好了

**Comment by smileCH** [comment]
你好，是这样的现在有好几个组件都用到了一些公用的activity，比如说A组件、B组件、C组件中都共用着联系人列表，日历、城市列表等activity，这些activity都是公用的，没做组件化之前都是放到一个common包下的，供不同业务调用，现在改装成组件化的话，如果把这些公用的activity放到其中的一个组件(比如A组件中)，其他组件用到的话可以通过路由进行通信，但是多人协作的时候是需要把这些组件都上传到仓库的，比如同事甲开发B组件，那么这些通用的activity都放在A组件中了，要想使用也必须引用A组件，这样就耦合了，不知道是否表达清楚了

**Comment by wustor** [comment]
如果一个类被2个或者以上的组件使用到，那么就应该下沉到library中，所以你下沉就好了
